[general]
working_directory = "/home/masef3/"

[window]
startup_mode = "Maximized"
decorations = "Full"
title = "MAGIC MIND TRANSPORTER"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 0
y = 0

[font]
size = 10.0
normal = { family = "Iosevka", style = "Regular" }

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[cursor.style]
shape = "Block"

[terminal.shell]
program = "/bin/bash"

[mouse]
hide_when_typing = true



